// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzitpxtmvakgebbpqiuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6aXRweHRtdmFrZ2ViYnBxaXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDkxNzgsImV4cCI6MjA2NzY4NTE3OH0.Zr2ht9gpWDg00HWeJE1kTJMJwWV1LOOeISIeelejReE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});